### ISSUE TITLE
PathAbs constructor cleanup

### ISSUE THREAD

**Issue by Screwtapello** [vitiral/path_abs#29]
Currently, there are a bunch of different ways to construct a `PathAbs`:

- `PathArc::absolute()` constructs a `PathAbs` using lexical canonicalization
- `PathAbs::new()` has a docstring that implies it uses `std::fs::canonicalize()` but actually calls `PathArc::absolute()`.
- `PathAbs::mock()` constructs a `PathAbs` but doesn't actually validate its absoluteness

I think these could be cleaned up/rationalized. For example:

- `PathAbs::new()` should take a path and validate that it conforms to the rules for absolute paths, returning an error if something's wrong
    - Normally `new()` is for the most commonly-used constructor, but I'm not sure any of them are obviously the best
    - "validate in `new()`" follows standard library types like `std::ptr::NonNull`
- `PathAbs::new_with_canonicalization()` should take a path and call `std::fs::canonicalize()` on it
    - Not currently a supported constructor, but if it's in the standard library people will be surprised if this crate doesn't support it at all
- `PathAbs::new_with_parents_removed()` should resolve `..` components by removing the previous component, like `PathArc::absolute()` does today
- Delete `PathAbs::mock()`
    - somebody who wants a path for testing can use [the tempfile crate](https://crates.io/crates/tempfile)
    - if this method is really needed, we can rename it to `PathAbs::new_unchecked()` after the model of `std::ptr::NonNull`
- Delete `PathArc::absolute()`
    - `PathArc` is kind of a behind-the-scenes type (see #18) and doesn't need any more attention drawn to it
    - people who want to turn a `PathArc` into a `PathAbs` can use one of the direct constructors

This would also provide a natural place for `PathAbs::new_with_parents_resolved()` to slot in, from #20.

**Comment by vitiral** [comment]
I agree with a lot of this. Do note that releasing this will require a major version bump since it is breaking backwards compatibility.

Some comments:
- Delete `PathArc::absolute()`: the reason this exists is because `Path::absolute` exists and this overrides it. If we remove `Deref` then it might not be an issue anymore. I need to think more about the part which `PathArc` and `Deref` plays.
- `PathAbs::new()`: the docstring should be fixed for sure. I'm not sure if throwing an error if it isn't already an absolute path is the best thing here. I need to think about it more, but I'm leaning towards just fixing the docsftring.
- `PathAbs::new_with_canonicalization()`: do you think this can be named `PathAbs::canonicalized`? This would be similar verbiage to the `sorted` std function for python. I'm not sure if there is equivalents in rust.
- `PathAbs::new_with_parents_removed()`: I agree this constructor should exist but I'm not sure about the name. Some ideas: `PathAbs::walked`, `PathAbs::resolved`. `resolved` would kinda-sorta follow the [python function](https://docs.python.org/3/library/pathlib.html#pathlib.Path.resolve), although that also resolves symlinks (but has `strict=False` behavior which allows non-existent paths... it's weird). The idea is that it differs from `PathAbs::new` by "resolving" `..` elements instead of removing them syntactically. Maybe calling it `PathAbs::parents_resolved` would be okay as well.
- `PathAbs::mock()`: I'm okay naming this `new_unchecked()`. I think providing a way to unit test without filesystem calls is important to this library, and `new_unchecked` would also let us get some performance gains for internal methods.

Also I use `PathArc` quite a bit for it's serialization abilities, especially when communicating with webapps. I'm not sure what the right thing to do here is. Note that the webapp use case does NOT want to actually resolve any paths, so keeping everything as `PathArc` is better.

It's possible that serialization in general is an overloaded feature of this library and should be split into it's own library (`path_ser` maybe?). I'm not totally sure but it's at least worth considering.
