### ISSUE TITLE
windows path handling

### ISSUE THREAD

**Issue by vitiral** [vitiral/path_abs#34]
@zilbuz opened a bug in vitiral/artifact#247. They mentioned that it might be better addressed in `path_abs` and I agree.

Looking at https://docs.microsoft.com/fr-fr/windows/desktop/FileIO/naming-a-file#maxpath, it doesn't look like windows even allows `'/'` to be in the name of a file or a directory, so I don't see any harm in converting them. Honestly I thought we already did this.

**Comment by vitiral** [comment]
@Screwtapello thoughts?

**Comment by Screwtapello** [comment]
The various path-manipulation routines I've written all tend to iterate over `path.components()` rather than manually concatenating strings at least in part because of this: `path.components()` and `PathBuf::push()` will always do the Right Thing with respect to path separators on the current platform, and they're tested thoroughly by the Rust project itself. Any kind of `#[cfg(windows)]` code we write ourselves won't get tested nearly as thoroughly.

I really need to get around to making PRs for the rest of my trait-rework branch; it uses `path.components()` extensively.

**Comment by vitiral** [comment]
sounds good. Let me know if you need any help!

This is a serious pain point for writing software using user-specified paths. It's good to see how `path_abs` can make a positive impact by abstracting away doing the right thing... especially when doing the right thing is annoying.
