### ISSUE TITLE
Idea: Give FileWrite a `write_fmt` inherent method

### ISSUE THREAD

**Issue by ExpHP** [vitiral/path_abs#8]
```rust
impl FileWrite {
    pub fn write_fmt(&mut self, fmt: fmt::Arguments) -> fmt::Result<()>
    { ... }
}
```

A `write_fmt` inherent method makes writing more ergonomic by **allowing the `write!` macros to be used without importing `std::io::Write`.**  The trick here is that the write! macros are effectively duck-typed; [this fact is documented](https://doc.rust-lang.org/std/macro.write.html), and it's the reason why [you can write to a `fmt::Formatter` without importing anything](https://doc.rust-lang.org/std/fmt/struct.Formatter.html#method.write_fmt).

**Comment by vitiral** [comment]
Huh, neat trick. 

I am hesitant to expand the API to avoid importing the `std::io::Write` trait. IMO that should _always_ be imported and requiring the user to import it is a big ergonomic miss of rust ATM (a miss that `ergo` is trying to resolve).

I could _maybe_ consider implementing this as `doc(hidden)` so that it doesn't expand the API but also improves the ergonomics. Thoughts?

**Comment by ExpHP** [comment]
> I could maybe consider implementing this as doc(hidden) so that it doesn't expand the API but also improves the ergonomics. Thoughts?

I feel that would be too mysterious.  (then again, I doubt many people would ever stop to think about it for long.)

> I am hesitant to expand the API to avoid importing the std::io::Write trait. IMO that should always be imported and requiring the user to import it is a big ergonomic miss of rust ATM (a miss that ergo is trying to resolve).

Sounds fair enough.  I haven't stared too hard at the rest of the ergo ecosystem yet but if you feel this problem is better addressed elsewhere that seems fine to me.
